import { Inter } from 'next/font/google'
import { AuthUserProvider } from './auth'
import '../styles/app.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'giphy',
  description: 'Giphy App -- Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthUserProvider >
          <>
            {children}
          </>
        </AuthUserProvider>
      </body>
    </html>
  )
}
